---
name: Lint Project

on:
  pull_request_target:
    branches: ["dependabot/**"]

  pull_request:
    types: [opened, synchronize, edited]

  merge_group:
  workflow_dispatch:

permissions: read-all

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code

        uses: actions/checkout@v4.1.7
        with:
          # Get all history to be able to identify changed files
          fetch-depth: 0
      # Runs the Super-Linter action
      - name: Run Super-Linter
        # run the step only when base_ref(target branch name) is not null or branch name is not main
        if: ${{ github.base_ref || github.ref_name != github.event.repository.default_branch}}
        uses: super-linter/super-linter@v8.0.0
        env:
          # only log identified linting issues
          LOG_LEVEL: NOTICE
          # Only lint new and modified files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref || 'main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
